apm install Stylus
apm install Sublime-Style-Column-Selection
apm install atom-alignment
apm install atom-beautify
apm install autocomplete-paths
apm install autocomplete-ruby
apm install file-icons
apm install highlight-selected
apm install language-docker
apm install language-ejs
apm install language-haskell
apm install language-jade
apm install language-markdown
apm install language-slim
apm install language-vue
apm install linter
apm install linter-eslint
apm install linter-js-yaml
apm install linter-ruby
apm install markdown-scroll-sync
apm install pigments
apm install sort-lines
apm install tidy-markdown
apm install vim-mode
apm install wordcount
