[general]
import = [
    "~/.config/alacritty/themes/iceberg.toml"
]

[font]
size = 13.0
normal.family = "Hack Nerd Font"

[window]
padding = { x = 8, y = 4 }
option_as_alt = "Both"

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
action = "SelectNextTab"

[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
action = "SelectPreviousTab"
